name: Simple CI Test

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    name: Simple Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test frontend
      working-directory: ./frontend
      run: |
        echo "Testing frontend..."
        npm ci
        npm run build
    
    - name: Test backend
      working-directory: ./backend
      run: |
        echo "Testing backend..."
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        python -c "import fastapi; print('Backend test passed')" 